# Generated by Django 2.2.6 on 2021-09-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210927_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Building'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassroomType'),
        ),
    ]
